# Generated by Django 5.1 on 2026-04-19 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="QAR_PostProcess_Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "qar_id",
                    models.CharField(
                        db_index=True, max_length=60, verbose_name="QAR ID"
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[("upload", "上传后处理"), ("delete", "删除后处理")],
                        db_index=True,
                        max_length=16,
                        verbose_name="任务类型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("running", "处理中"),
                            ("success", "成功"),
                            ("failed", "失败"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                        verbose_name="任务状态",
                    ),
                ),
                ("attempt_count", models.IntegerField(default=0, verbose_name="尝试次数")),
                ("max_retries", models.IntegerField(default=2, verbose_name="最大重试次数")),
                (
                    "last_error",
                    models.TextField(blank=True, null=True, verbose_name="最后错误信息"),
                ),
                (
                    "mask_min_row_id",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="掩码增量起始行ID"
                    ),
                ),
                (
                    "mask_max_row_id",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="掩码增量结束行ID"
                    ),
                ),
                (
                    "created_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "started_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="开始时间"),
                ),
                (
                    "finished_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="结束时间"),
                ),
                (
                    "updated_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "QAR后处理任务",
                "verbose_name_plural": "QAR后处理任务",
                "indexes": [
                    models.Index(
                        fields=["qar_id", "task_type", "created_time"],
                        name="core_qar_po_qar_id_d47807_idx",
                    ),
                    models.Index(
                        fields=["status", "updated_time"],
                        name="core_qar_po_status_f8bd2e_idx",
                    ),
                ],
            },
        ),
    ]
