"""
Django settings for CAUC_FOQA project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
from datetime import timedelta
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-p%q9+41x6hpxlehrp5b3@gn9pk7=%z=et&4*7l)cb^toxtv&n%"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'django.contrib.humanize',
    
    # Custom Apps
    "apps.core",
    "apps.authentication",
    "apps.api.apps.ApiConfig",

    # Third-party Apps
    "import_export",
    "tailwind",
    "bulk_signals",
    "corsheaders",
    "rest_framework",
    "rest_framework_simplejwt",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    # "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        'ENGINE': os.getenv('DB_ENGINE'),
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Media files (user-uploaded content)
MEDIA_URL = '/media/image/'
MEDIA_ROOT = Path(BASE_DIR, 'media')

# Tailwind CSS settings
TAILWIND_APP_NAME = 'users'
TAILWIND_CSS_PATH = 'css/styles.css'

# Import-Export settings
# https://django-import-export.readthedocs.io/en/latest/settings.html
IMPORT_EXPORT_USE_TRANSACTIONS = True  # 默认值为False。它确定库是否会在数据导入中使用数据库事务，以确保安全。


# Custom settings for date and datetime formats
DATE_INPUT_FORMATS = [
    '%Y-%m-%d',  # 2023-08-09
    '%Y/%m/%d',  # 2023/08/09
    '%d/%m/%Y',  # 2023/08/09
    # 其他日期格式
]

DATETIME_INPUT_FORMATS = [
    '%Y-%m-%d %H:%M:%S',  # 2023-08-09 00:00:00
    '%Y-%m-%d %H:%M',     # 2023-08-09 00:00
    '%Y/%m/%d %H:%M:%S',  # 2023/08/09 00:00:00
    '%Y/%m/%d %H:%M',     # 2023/08/09 00:00
    '%d/%m/%Y %H:%M:%S',  # 2023/08/09 00:00:00
    '%d/%m/%Y %H:%M',     # 2023/08/09 00:00
    # 其他日期时间格式
]

# Frontend base URL used by legacy Django routes to redirect into the SPA
FRONTEND_BASE_URL = os.getenv('FRONTEND_BASE_URL', 'http://127.0.0.1:5173')

# Upstream FastAPI endpoint for streaming flight risk inference
FLIGHT_RISK_STREAM_UPSTREAM_URL = os.getenv(
    'FLIGHT_RISK_STREAM_UPSTREAM_URL',
    'http://127.0.0.1:8001/api/v1/flight-risk/stream',
)

FLIGHT_RISK_STREAM_JSON_UPSTREAM_URL = os.getenv(
    'FLIGHT_RISK_STREAM_JSON_UPSTREAM_URL',
    'http://127.0.0.1:8001/api/v1/flight-risk/stream-json',
)

IMPUTATION_TRAIN_STREAM_UPSTREAM_URL = os.getenv(
    'IMPUTATION_TRAIN_STREAM_UPSTREAM_URL',
    'http://127.0.0.1:8002/api/v1/imputation/train/stream',
)

IMPUTATION_TRAIN_UPSTREAM_URL = os.getenv(
    'IMPUTATION_TRAIN_UPSTREAM_URL',
    'http://127.0.0.1:8002/api/v1/imputation/train',
)

IMPUTATION_TRAIN_HYPERPARAMS_UPSTREAM_URL = os.getenv(
    'IMPUTATION_TRAIN_HYPERPARAMS_UPSTREAM_URL',
    'http://127.0.0.1:8002/api/v1/imputation/train/hyperparams',
)

IMPUTATION_REPAIR_STREAM_UPSTREAM_URL = os.getenv(
    'IMPUTATION_REPAIR_STREAM_UPSTREAM_URL',
    'http://127.0.0.1:8002/api/v1/imputation/stream/repair',
)

IMPUTATION_REPAIR_STREAM_JSON_UPSTREAM_URL = os.getenv(
    'IMPUTATION_REPAIR_STREAM_JSON_UPSTREAM_URL',
    'http://127.0.0.1:8002/api/v1/imputation/stream/repair-json',
)


# Frontend/Backend separation settings
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 50,
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": False,
    "AUTH_HEADER_TYPES": ("Bearer",),
}