"""Parameter metadata shared by monitoring policy and stats calculation."""

VISUALIZATION_PARAMETER_SET = {
    # speed-acceleration
    "dGroundspeed",
    "dTAS",
    "dMach",
    "dU",
    "dV",
    "dW",
    "dUkDot",
    "dVkDot",
    "dWkDot",
    # attitude-angle
    "dAlpha",
    "dBeta",
    "dPhi",
    "dTheta",
    "dPsi",
    "dChi",
    "dGamma",
    # position-height
    "dLongitude",
    "dLatitude",
    "dASL",
    "dAGL",
    "dPosXg",
    "dPosYg",
    "dPosZg",
    # external-control
    "dtx",
    "dty",
    "dtz",
    "LGPos",
    "dFlap",
    # aircraft-load
    "dNx",
    "dNy",
    "dNz",
    # fuel-engine
    "gfuel",
    "gfused",
    "dGtNormal",
    "dGfNormal",
    "dGFuel",
    "pe_t1",
    "pe_t2",
    "rot1",
    "rot2",
    "thrust",
}

PARAMETER_UNIT_MAP = {
    "dSimTime": "s",
    "dStepTime": "s",
    "dGravityAcc": "m/s^2",
    "dUwg": "m/s",
    "dVwg": "m/s",
    "dWwg": "m/s",
    "dUTrub": "m/s",
    "dVTrub": "m/s",
    "dWTrub": "m/s",
    "dMass": "kg",
    "dGroundspeed": "kt",
    "dTAS": "kt",
    "dMach": "Mach",
    "dPd": "Pa",
    "dPs": "Pa",
    "dUk": "m/s",
    "dVk": "m/s",
    "dWk": "m/s",
    "dU": "m/s",
    "dV": "m/s",
    "dW": "m/s",
    "dUkDot": "m/s^2",
    "dVkDot": "m/s^2",
    "dWkDot": "m/s^2",
    "dP": "deg/s",
    "dQ": "deg/s",
    "dR": "deg/s",
    "dPRad": "rad/s",
    "dQRad": "rad/s",
    "dRRad": "rad/s",
    "dRDot": "deg/s^2",
    "dPDot": "deg/s^2",
    "dQDot": "deg/s^2",
    "dAlpha": "deg",
    "dAlphaRad": "rad",
    "dSinAlpha": "1",
    "dCosAlpha": "1",
    "dAlphaDot": "deg/s",
    "dBeta": "deg",
    "dBetaRad": "rad",
    "dSinBeta": "1",
    "dCosBeta": "1",
    "dBetaDot": "deg/s",
    "dPhi": "deg",
    "dTheta": "deg",
    "dPsi": "deg",
    "dChi": "deg",
    "dGamma": "deg",
    "dLongitude": "deg",
    "dLatitude": "deg",
    "dASL": "m",
    "dAGL": "m",
    "dPosXg": "m",
    "dPosYg": "m",
    "dPosZg": "m",
    "dtx": "deg",
    "dty": "deg",
    "dtz": "deg",
    "LGPos": "%",
    "dFlap": "deg",
    "dNx": "g",
    "dNy": "g",
    "dNz": "g",
    "dUkgDot": "m/s^2",
    "dVkgDot": "m/s^2",
    "dWkgDot": "m/s^2",
    "dUkg": "m/s",
    "dVkg": "m/s",
    "dWkg": "m/s",
    "dTrueHeading": "deg",
    "dMagHeading": "deg",
    "gfuel": "kg",
    "gfused": "kg",
    "dGtNormal": "kg/s",
    "dGfNormal": "kg",
    "dGFuel": "kg",
    "pe_t1": "%",
    "pe_t2": "%",
    "rot1": "rpm",
    "rot2": "rpm",
    "thrust": "N",
    "dDa": "%",
    "dDr": "%",
    "dDe": "%",
    "dDaTrim": "%",
    "dDeTrim": "%",
}
